language: java
services:
  - docker

branches:
  only: 
    - master

stages:
  - compile
  - test

jobs:
  include:
    - stage: compile
      name: "Compile server project"
      script: mvn package -DskipTests -f server/pom.xml
    - stage: compile
      name: "Compile client project"
      script: mvn package -DskipTests -f client/pom.xml
    - stage: test
      name: "Test server project"
      script: mvn test -f server/pom.xml
    - stage: test
      name: "Test client project"
      script: mvn test -f client/pom.xml