language: java
jdk:
  - openjdk8
services:
  - docker

stages:
  - compile
  - test
  - qa

cache:
  directories:
    - $HOME/.m2

jobs:
  include:
    - stage: compile
      name: "Compile server project"
      install: true
      script: mvn package -DskipTests -f server/pom.xml
    - stage: compile
      name: "Compile client project"
      install: true
      script: mvn package -DskipTests -f client/pom.xml
    - stage: test
      name: "Test server project"
      install: true
      script: mvn test -f server/pom.xml
    - stage: test
      name: "Test client project"
      install: true
      script: mvn test -f client/pom.xml
    - stage: qa
      addons:
        sonarcloud:
          organization: "edineipiovesan-github"
          token:
            secure: $SONAR_TOKEN
      script:
        - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar