version: "3"
services:
  maven:
    image: maven:3-jdk-8-alpine
    volumes: 
      - .:/usr/src/mymaven 
      - $HOME/.m2:/root/.m2
    working_dir: /usr/src/mymaven
    command: mvn package -DskipTests