version: "3"
services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: poc-rabbit
    ports: 
      - 5672:5672
      - 9090:15672
    environment: 
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=pass
    networks: 
      - backend
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:9090"]
      interval: 30s
      timeout: 10s
      retries: 5

  server-1:
    build: 
      context: ./server
      args: 
        - JAR_FILE=target/server-0.0.1-SNAPSHOT.jar
    container_name: server-1
    ports: 
      - 8090:8080
    networks: 
      - backend
    depends_on: 
      - rabbitmq

  server-2:
    build: 
      context: ./server
      args: 
        - JAR_FILE=target/server-0.0.1-SNAPSHOT.jar
    container_name: server-2
    ports: 
      - 8091:8080
    networks: 
      - backend
    depends_on: 
      - rabbitmq

  server-3:
    build: 
      context: ./server
      args: 
        - JAR_FILE=target/server-0.0.1-SNAPSHOT.jar
    container_name: server-3
    ports: 
      - 8092:8080
    networks: 
      - backend
    depends_on: 
      - rabbitmq

  server-4:
    build: 
      context: ./server
      args: 
        - JAR_FILE=target/server-0.0.1-SNAPSHOT.jar
    container_name: server-4
    ports: 
      - 8093:8080
    networks: 
      - backend
    depends_on: 
      - rabbitmq

  client-1:
    build: 
      context: ./client
      args: 
        - JAR_FILE=target/client-0.0.1-SNAPSHOT.jar
    container_name: client-1
    ports: 
      - 8098:8080
    networks: 
      - backend
    depends_on: 
      - rabbitmq

  client-2:
    build: 
      context: ./client
      args: 
        - JAR_FILE=target/client-0.0.1-SNAPSHOT.jar
    container_name: client-2
    ports: 
      - 8099:8080
    networks: 
      - backend
    depends_on: 
      - rabbitmq

networks: 
  backend: 
    driver: bridge