version: "3"
services:
  maven:
    image: maven:3-jdk-8-alpine
    volumes: 
      - .:/usr/src/mymaven 
      - $HOME/.m2:/root/.m2
      - ./server/target:/usr/src/mymaven/server/target
      - ./client/target:/usr/src/mymaven/client/target
    working_dir: /usr/src/mymaven
    command: mvn package -DskipTests