version: "3.3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: server-application
    ports:
      - "8081:8080"
  app2:
    build:
      context: .
      dockerfile: Dockerfile
    image: server-application
    ports:
      - "8082:8080"
  app3:
    build:
      context: .
      dockerfile: Dockerfile
    image: server-application
    ports:
      - "8083:8080"
  app4:
    build:
      context: .
      dockerfile: Dockerfile
    image: server-application
    ports:
      - "8084:8080"
  app5:
    build:
      context: .
      dockerfile: Dockerfile
    image: server-application
    ports:
      - "8085:8080"
  app6:
    build:
      context: .
      dockerfile: Dockerfile
    image: server-application
    ports:
      - "8086:8080"